# Matrix

- Unlike vector which is a one dimensional array, matrix is a **two dimensional array that consists of row and column**
- we can express matrix as an array : A = ((a1.1,a1.2),(a2.1,a2.2),(a3.1,a3.2))
- we can transform an array into matrix as long as the array is 2 dimensional. Meaning, in an array there is an array.
- dimensi data --> banyaknya kolom
- beda antara dimensi data dengan dimensi array

In [1]:
import numpy as np

In [5]:
data_1 = [1,2,3] #ini 1-D Array alias vektor. karena di dalam array langsung data.
data_2 = [[1,2,3],[4,5]] #ini 2-D array. karena di dalam array ada array. tapi ini bukan matrix
#data_2 bukan matrix. karena array yang ada di dalam arraynya, berbeda jumlahnya. kalo mau jadi matrix harus sama jumlah elemennya
data_3 = [[1,2,3], [4,5,6]] #ini 2-D array yang berupa matrix

In [6]:
vec = np.array(data_1)
vec

array([1, 2, 3])

In [7]:
data = np.array(data_2)
data

C:\Users\yevaw\AppData\Local\Temp\ipykernel_11532\1707392955.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array(data_2)


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [8]:
mat = np.array(data_3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#definisi matriks
data = [[1,2], [3,4], [5,6], [7,8]] #pastikan jumlah elemen di list dalam sama
data_mat = np.array(data)
data_mat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Types of Matrix
- Square matrix 
- Upper Triangle Matrix
- Lower Triangle Matrix
- Diagonal Matrix
- Identity Matrix

In [17]:
X = ([4,9,2], [3,5,7], [8,1,6])
np.array(X) #square


array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [16]:
np.triu(X) #upper triangle

array([[4, 9, 2],
       [0, 5, 7],
       [0, 0, 6]])

In [18]:
np.tril(X)

array([[4, 0, 0],
       [3, 5, 0],
       [8, 1, 6]])

In [19]:
np.diag(X)

array([4, 5, 6])

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matrix bisa ditambah atau dikurangkan dengan matrix lainnya. Selama **ukurannya sama**.

In [28]:
x_mat = ([4,9,2], [3,5,7], [8,1,6])
y_mat = ([3,10,11], [7,8,12], [6,9,10])

#matriks di definisikan dengan huruf kapital besar 1
X = np.array(x_mat) 
Y = np.array(y_mat)

Z = X + Y
print(Z)

D = X  - Y
print(D)

[[ 7 19 13]
 [10 13 19]
 [14 10 16]]
[[ 1 -1 -9]
 [-4 -3 -5]
 [ 2 -8 -4]]


### Matrix Multiplication
1. Matrix - Scalar
2. Hadamard Product
3. Matrix-Matrix

Matrix - Scalar

In [29]:
X

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [31]:
A = 2*X
A

array([[ 8, 18,  4],
       [ 6, 10, 14],
       [16,  2, 12]])

Hadamard Product

- Perkalian yang sifatnya sama dengan operasi penjumlahan dan pengurangan. Per elemen di kalikannya.
- Simbolnya o.
- Bukan perkalian yang bisa menghasilkan invers.

In [33]:
print(X)
print(Y)

[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[ 3 10 11]
 [ 7  8 12]
 [ 6  9 10]]


In [34]:
X * Y

array([[12, 90, 22],
       [21, 40, 84],
       [48,  9, 60]])

Matrix-Matrix

- perkalian matrix biasa dalam alin. kayak dot product b1 dengan k1, dst(a1.1 x b1.1 + a1.2 x b2.1)
- jumlah kolom di matriks pertama hrus sama dengan jumlah baris di matriks kedua (matriks 3x2 bisa dioperasikan dengan 2x2. tapi matriks 2x2 tidak bisa dioperasikan dengan 3x2)

In [42]:
print(X)
print(Y)

print(X@Y)


[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[ 3 10 11]
 [ 7  8 12]
 [ 6  9 10]]
[[ 87 130 172]
 [ 86 133 163]
 [ 67 142 160]]


In [45]:
A =[[1,2], [3,4], [5,6]]
B =[[5,6,7], [8,9,3]]

A = np.array(A)
B = np.array(B)

In [48]:
A.shape

(3, 2)

In [49]:
B.shape

(2, 3)

In [46]:
print(A@B)

[[21 24 13]
 [47 54 33]
 [73 84 53]]


In [47]:
print(B@A)

[[58 76]
 [50 70]]


Matrix Division (Hadamard)

In [50]:
print(X)
print(Y)

[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[ 3 10 11]
 [ 7  8 12]
 [ 6  9 10]]


In [51]:
print(X/Y)

[[1.33333333 0.9        0.18181818]
 [0.42857143 0.625      0.58333333]
 [1.33333333 0.11111111 0.6       ]]


Transpose
- Flip the columns and rows
- Mostly to manipulate the shape so it can be operable

In [52]:
print(X)
E = X.T
print(E)

[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[4 3 8]
 [9 5 1]
 [2 7 6]]


Inverse

- Mencari matriks lain dari suatu matriks yang akan menjadikan matriks identitas saat dikalikan dengan matriks asal.
- A1 = inverse dari matriks A. saat A x A-1 = matriks identitas.

In [53]:
print(X)

[[4 9 2]
 [3 5 7]
 [8 1 6]]


In [54]:
from numpy.linalg import inv
inv_X = inv(X)
inv_X

array([[ 0.06388889, -0.14444444,  0.14722222],
       [ 0.10555556,  0.02222222, -0.06111111],
       [-0.10277778,  0.18888889, -0.01944444]])

In [55]:
I = X@inv_X
print(I)

[[ 1.00000000e+00  0.00000000e+00 -3.46944695e-17]
 [ 1.24900090e-16  1.00000000e+00 -6.59194921e-17]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [57]:
inv_Y = inv(Y)
I1 = Y@inv_Y
I1

array([[ 1.00000000e+00,  5.55111512e-17,  1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00,  4.44089210e-16],
       [-1.66533454e-16, -1.11022302e-16,  1.00000000e+00]])

tidak semua matriks punya invers. misal matriks singular

contoh matriks singular (yang salah satu kolomnya adalah kelipatan kolom lainnya:)

In [61]:
S = np.array([[1,2], [2,4]])
inv(S)

LinAlgError: Singular matrix

matriks yang determinannya 0  juga tidak punya invers

### Determinant

In [60]:
from numpy import array
from numpy.linalg import det

In [62]:
det(S)

0.0

### Tensor
- matriks yang diletakkan didalam list
- array 3 dimensi
- ukuran matriks yang ada di dalam tensor harus sama semua

In [66]:
#A dan B ini matriks 2x2
A = np.array([[1,2], [7,8]])
B = np.array([[1,1], [1,1]])
print(A)
print(B)

[[1 2]
 [7 8]]
[[1 1]
 [1 1]]


In [67]:
tensor = [A, B]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [7, 8]],

       [[1, 1],
        [1, 1]]])

In [68]:
tensor.shape

(2, 2, 2)

yang atas maksudnya adalah ada 2 matriks dengan ukurang 2x2.

In [71]:
C = np.array([[1,2], [7,8], [1,1], [1,1]])
D = np.array([[1,1], [1,1], [1,1], [1,1]])
E = np.array([[1,1], [1,1], [1,1], [1,1]])

tensor1 = [C, D, E]
tensor1 = np.array(tensor1)
tensor1

array([[[1, 2],
        [7, 8],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [72]:
tensor1.shape

(3, 4, 2)

ada 3 matriks dengan ukuran 4x2

#### Tensor ini nama umum. yang 1D dan 2D ada namanya sendiri. lebih dari itu namanya sama. yaitu tensor.

- Vektor : 1 -D array : 1 -D tensor
- matriks : 2-D array : 2-D tensor