## NG Challenge 4

1. Buatlah Tensor dibawah ini dengan Python : [[23, 50, 7, 12], [57, 67, 99, 43], [75, 21, 57, 12], [87, 26, 18, 84]]


In [4]:
#import numpy
import numpy as np
from numpy import array

In [8]:
#create the tensor
tensor1 = array([[[23, 50], [7, 12]], [[57, 67], [99, 43]], [[75, 21], [57, 12]], [[87, 26], [18, 84]]])

In [9]:
#print the tensor
print(tensor1)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


In [10]:
print(tensor1.shape)

(4, 2, 2)


2. Lakukan perkalian terhadap matrix berikut :
- A = [[[23, 50, 19], [7, 12, 109], [57, 67, 98]]]
- B = [[17], [22], [19]]

In [15]:
#define the matrix
A = np.array([[[23, 50, 19], [7, 12, 109], [57, 67, 98]]])
B = np.array([[17], [22], [19]])

print(A)
print(A.shape)

print(B)
print(B.shape)

[[[ 23  50  19]
  [  7  12 109]
  [ 57  67  98]]]
(1, 3, 3)
[[17]
 [22]
 [19]]
(3, 1)


In [16]:
#multiply
AmulB = A@B
print(AmulB)
print(AmulB.shape)

[[[1852]
  [2454]
  [4305]]]
(1, 3, 1)


3. Lakukan transpose, hitung determinan dan inverse terhadap matrix di bawah ini:
- A = [[[23,50,19], [7, 12, 109], [57,57,98]]]

In [18]:
#define the matrix
A = np.array([[[23,50,19], [7, 12, 109], [57,57,98]]])
print(A)
print(A.shape)

[[[ 23  50  19]
  [  7  12 109]
  [ 57  57  98]]]
(1, 3, 3)


In [20]:
#tranpose
Atransp = A.T
print(Atransp)
print(Atransp.shape)

#determinan
from numpy.linalg import det #import determinant from numpy
detA = det(A)
print(detA)

#inverse
from numpy.linalg import inv #import inverse from numpy
invA = inv(A)
print(invA)
print(invA.shape)

[[[ 23]
  [  7]
  [ 57]]

 [[ 50]
  [ 12]
  [ 57]]

 [[ 19]
  [109]
  [ 98]]]
(3, 3, 1)
[155084.]
[[[-0.03247917 -0.02461247  0.03367207]
  [ 0.03563875  0.00755075 -0.01530783]
  [-0.00183771  0.00992365 -0.00047716]]]
(1, 3, 3)
