## NG Challenge 5

- Apakah [[1], [3]] adalah eigenvector dari [[1, -1], [6, 4]]?
- Jika iya, berapakah eigenvaluenya?

In [1]:
import numpy as np

In [5]:
#define the matrix
A = np.array([[1, -1], [6, 4]])
print(A)
print(A.shape)

[[ 1 -1]
 [ 6  4]]
(2, 2)


In [6]:
from numpy.linalg import eig
eigval, eigvec = eig(A)

In [7]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [8]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])