### NG Challenge 3

1. Buatlah vektor di bawah ini dengan Python
(17, 22, 19)


In [1]:
# import numpy
import numpy as np

In [2]:
#define the vector
a = np.array([17,22,19])

In [4]:
#print the vector
print(a)

[17 22 19]


2. Diberikan 3 buah vektor 3D:
- A = (17, 22, 19)
- B = (10, 20, 11)
- C = (5, 12, 9)

Hitunglah :
- A + B
- B - C
- A dot C
- A x B
- norm A
- Sudut antara vektor A dan B

In [5]:
b = np.array([10,20,11])
c = np.array([5, 12, 9])
print(a)
print(b)
print(c)


[17 22 19]
[10 20 11]
[ 5 12  9]


In [8]:
aplusb = a + b
bminc = b - c
adotc = a@c
atimesb = a*b
print(aplusb)
print(bminc)
print(adotc)

[27 42 30]
[5 8 2]
520


In [9]:
#norm A
a_norm = np.linalg.norm(a)
print(a_norm)

33.67491648096547


In [10]:
#getting the angle between a and b
print(a)
print(b)

[17 22 19]
[10 20 11]


In [13]:
unit_a = a/np.linalg.norm(a) #make the vector a into unit vector
unit_b = b/np.linalg.norm(b) #make the vector b into unit vector

dot_ab = np.dot(unit_a, unit_b) #use a dot operation between unit vec a and b

angle = np.arccos(dot_ab) #get the angle from it
print(angle)

0.21971776576153962
