# Vektor

- kalau dalam dunia data science, 1 data itu 1 vektor.


In [2]:
a = [1,2,3,4,5,]
b = [6,7,8,9,10]

In [3]:
a + b #kalo cuma + biasa, jadinya begini:

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
#kalo pakai vektor
import numpy as np
vect_a = np.array(a)
vect_b = np.array(b)

vect_a + vect_b

array([ 7,  9, 11, 13, 15])

#### Vector norm
magnitude (besaran) dari vektor

In [10]:
vect_a = np.array([3, 4])
np.linalg.norm(vect_a, 2) #angka 2 disini maksudnya pakai l2 yaitu euclidean.(defaultnya 2)
#kalo mau pake manhattan, pake 1. 
np.linalg.norm(vect_a, 1)

7.0

#### Operasi Vektor
1. Penjumlahan/Pengurangan/Pembagian

A. Di operasikan dengan bilangan

In [11]:
vect_a = np.array([1,2,3])
vect_a + 2

array([3, 4, 5])

In [12]:
vect_a - 2

array([-1,  0,  1])

In [13]:
vect_a / 2

array([0.5, 1. , 1.5])

B. Dioperasikan antar Vektor

In [14]:
vect_b = np.array([10,11,12])

In [15]:
vect_a + vect_b

array([11, 13, 15])

In [16]:
vect_a - vect_b

array([-9, -9, -9])

In [17]:
vect_a / vect_b

array([0.1       , 0.18181818, 0.25      ])

In [18]:
vect_c = ([1,2])

untuk penjumlahan antar vektor, harus sama jumlahnya. kalo beda akan error :

In [19]:
vect_c + vect_b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

2. Perkalian

A. Dikalikan dengan Bilangan

In [24]:
vect_a

array([1, 2, 3])

In [25]:
vect_a * 3

array([3, 6, 9])

B. Dikalikan antar Vektor (Vector Multiplication)

In [26]:
vect_d = ([4,5,6])
vect_a * vect_d

array([ 4, 10, 18])

C. Dot Product

In [28]:
np.dot(vect_a, vect_d)

32

In [29]:
vect_a.dot(vect_d)

32

In [30]:
vect_a@vect_d

32

##### Cosine Similarity

In [32]:
vect_f = np.array([4,0])
vect_g = np.array([6, 0])

In [36]:
#membuktikan bahwa saat 2 vektor itu sejajar, nilai cos = 1
cos_theta = (vect_f.dot(vect_g))/(np.linalg.norm(vect_f) * np.linalg.norm(vect_g))
cos_theta

1.0

In [39]:
rad = np.arccos(cos_theta)
rad

0.0

In [40]:
degree = np.degrees(rad)
degree

0.0

#### Study Case
Plagiarism detection

In [42]:
teks_1 = "saya pergi ke rumah nenek saya"
teks_2 = "saya pergi ke rumah kakek saya"

In [45]:
teks_1 = [2,1,1,1,1,0] #mengubah dari string ke numbers
teks_2 = [2,1,1,1,0,1]

vect_t1 = np.array(teks_1)
vect_t2 = np.array(teks_2)

cos_theta1 = (vect_t1@vect_t2)/(np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2)) #Mengecek kemiripan
cos_theta1

0.8749999999999998