# From

In [1]:
#import pake from
from nama import mingzi, daftar_nama
mingzi

'liu'

In [2]:
daftar_nama

['liu', 'fei', 'hong']

In [3]:
#untuk inisialiasi
from nama import mingzi as m

In [4]:
m

'liu'

# NumPy

### Numerical Python

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
np.empty(1)

array([0.0078125])

In [8]:
print(np.arange(2,10,2))
print(np.arange(2))

[2 4 6 8]
[0 1]


### Perbedaan List dengan Array

In [9]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight/height**2
#list nggak bisa langsung dibuat operasi

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [11]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
#ubah dulu ke array
np_height = np.array(height)
np_weight = np.array(weight)
np_weight/np_height**2
#array bisa dibuat kalkulasi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

##### Appending Array

In [12]:
arr = np.array([1,2,3,4,5])
np.append(arr, [6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr2 = np.array([1,2,3,7])
np.append(arr2, [6,7,8])

array([1, 2, 3, 7, 6, 7, 8])

In [15]:
panjang = np.array([1,2,3,4,5])
lebar = np.array([6,7,8,9,10])

panjang * lebar

array([ 6, 14, 24, 36, 50])

HATI-HATI

jangan nulis kayak gini

panjang = np.array=([1,2,3,4,5])

lebar = np.array=([6,7,8,9,10])

itu mengubah isinya si numpy arraynya

In [18]:
np.delete(arr, 3)

array([1, 2, 3, 5])

## Shape & Size

In [24]:
#0 dimensi
scalar = np.array(32)
print(scalar)
print(scalar.ndim)

32
0


In [22]:
#1 dimensi
vektor = np.array([1,2,3,4])
print(vektor)
print(vektor.ndim)

[1 2 3 4]
1


In [23]:
#2 dimensi
matriks = np.array([[1,2,3,4],
                     [5,6,7,8]])
print(matriks)
print(matriks.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [32]:
#3 dimensi
tridimensi = np.array([[[1,2,3,4,5],
                        [5,6,7,8,9]],

                        [[11,12,13,14,15],
                        [16,17,18,19,20]],

                        [[21,22,23,24,25],
                        [26,27,28,29,30]]])
print(tridimensi)
print(tridimensi.ndim)

[[[ 1  2  3  4  5]
  [ 5  6  7  8  9]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
3


In [47]:
#reshape
a = np.arange(6)

print(a)

b = a.reshape(3,2)

print(b)

c = a.reshape(6,1)

print(c)

#baris dan kolom. baris nyamping. kolom ke bawah

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [48]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[0 2 4]


In [49]:
f = a.view()
f

array([0, 1, 2, 3, 4, 5])

# Latihan

In [55]:
import numpy as np

np.arange(2,11)
print(np.arange(2,11))

x = np.arange(2, 11).reshape(3,3)
print(x)
print(x.ndim) #lihat berapa dimensi
print(x.shape) #lihat pola matriksnya

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
2
(3, 3)


In [57]:
arr = np.array(70)
print(arr)
print(arr.ndim)
print(arr.shape)

70
0
()


In [64]:
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(arr)
print(arr.shape) #lihat di tiap bracket itu dalamnya ada berapa matriks. makin ke kanan makin ke dalam
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [65]:
array_tes = np.array([[3,7,10,2], [3,7,10,2]], ndmin=4)
print(array_tes)
print(array_tes.ndim)
print(array_tes.shape)

[[[[ 3  7 10  2]
   [ 3  7 10  2]]]]
4
(1, 1, 2, 4)


In [67]:
array_tes = np.array([3,10,3,2])
print(array_tes[3] + array_tes[2])

5


In [102]:
arr = np.array([[6,7,8,9,10], [1,2,3,4,5]])
print(arr)
print(arr[-1,-1])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
5


In [101]:
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
print(arr[:2,0,0]) #tanda : adalah mengambil keseluruhan data. bisa berarti range.
#kalo range gapapa indexnya lebih (nanti yang kebaca yang mentokpaling besarnya)
#kalo : 3 berarti dari 0:3
#kalo 3: berarti dari 3 sampai akhir
print(arr.ndim)
print(arr.shape)

[1 7]
3
(2, 2, 3)


In [95]:
print(arr[:1,:2,1])

[[2 5]]


In [103]:
arr = np.array([4,5,6,7,1,2,3])
print(arr[1:6:4])

[5 2]


In [106]:
arr = np.array([2,2,7,4,5,6,7,8,10])
print(arr[2:8:3]) #START, END STEP
#print(arr[2:8]) #START, END (GAPAKAI STEP. GA LOMPAT)
print(arr[::3])

[7 6]
[2 4 7]


In [108]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [109]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,-1) #untuk ngebentuk ulang. -1 disini maksudnya adalah unknown dimension.
#unknown dimension ini berfungsi kalau kita tidak tahu dimensi yang belakangnya berapa
#jadi nanti yang mengisi unknown dimension itu adalah dari programnya
print(newarr, "\n")
print(newarr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

(2, 2, 3)
